<?php
	/**
	 * Set the content width in pixels, based on the theme's design and stylesheet.
	 *
	 * Priority 0 to make it available to lower priority callbacks.
	 *
	 * @global int $content_width
	 */
	function theme_content_width()
	{
		// This variable is intended to be overruled from themes.
		// Open WPCS issue: {@link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1043}.
		// phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound
		$GLOBALS['content_width'] = apply_filters('theme_content_width', 640);
	}
	add_action('after_setup_theme', 'theme_content_width', 0);
	
	/**
	 * Register widget area.
	 *
	 * @link https://developer.wordpress.org/themes/functionality/sidebars/#registering-a-sidebar
	 */
	function theme_widgets_init()
	{
		register_sidebar(array(
			'name' => esc_html__('Sidebar', 'popin'),
			'id' => 'sidebar-1',
			'description' => esc_html__('Add widgets here.', 'popin'),
			'before_widget' => '<section id="%1$s" class="widget %2$s">',
			'after_widget' => '</section>',
			'before_title' => '<h2 class="widget-title">',
			'after_title' => '</h2>',
		));
	}
	add_action('widgets_init', 'theme_widgets_init');
	
	/**
	 * Registers navigation menu locations for a theme.
	 */
	register_nav_menus(array(
		'primary-header' => esc_html__('Primary Header Nav', 'popin'),
		'primary-footer-left' => esc_html__('Primary Footer Nav Left', 'popin'),
	));
	
	/**
	 * Function for using Theme Image Assets Path
	 * <?php echo theme_images_dir() ?>
	 */
	function theme_images_dir()
	{
		return get_template_directory_uri() . '/dist/images';
	}
	
	/** Function to check if theme logo is included
	 * in theme asset/dist folder.
	 */
	function has_theme_logo()
	{
		if (file_exists(get_template_directory() . '/dist/images/global-header/logo.svg')) {
			return true;
		} else {
			return false;
		}
	}

/** Function to add class to links generated by next_post_link() and previous_post_link()
 *  @link https://css-tricks.com/snippets/wordpress/add-class-to-links-generated-by-next_posts_link-and-previous_posts_link/
 */	
	add_filter('next_posts_link_attributes', 'posts_link_attributes');
	add_filter('previous_posts_link_attributes', 'posts_link_attributes');

	function posts_link_attributes() {
			return 'class="button is-popin-purp"';
}
?>